version: '2'

services:
  nest:
    env_file:
      - .env
    build: .
    container_name: nestvisualblog
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: pnpm start:dev

  db:
    image: postgres:latest
    container_name: nestvisualblogdb
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - nestvisualblog-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  nestvisualblog-data:
  pgadmin-data:
